LMS/Controllers/QuizController.cs
using LMS.Helper;
using LMS.Models.Entities;
using LMS.Service.Abstract;
using LMS.ViewModels.QuizVM;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;

namespace LMS.Controllers
{
	public class QuizController : Controller
	{
		#region Fields
		private readonly IQuizService _quizService;
		private readonly IStudentQuizService _studentQuizService;
		private readonly IMediaService _mediaService;

		#endregion

		#region Ctor
		public QuizController(IQuizService quizService, IStudentQuizService studentQuizService, IMediaService mediaService)
		{
			_quizService = quizService;
			_studentQuizService = studentQuizService;
			_mediaService = mediaService;
		}
		#endregion

		#region Actions



		[HttpGet]
		public IActionResult Add(int id)
		{
			ViewBag.id = id;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Add(Quiz quiz)//make id = 0 
		{
			quiz.Id = 0;
			await _quizService.Add(quiz);
			return View();
		}
		[HttpGet]
		public IActionResult AddWritten(int id)
		{
			var obj = new AddWritten()
			{
				CourseId = id
			};
			return View(obj);
		}
		[HttpPost]
		public async Task<IActionResult> AddWritten(AddWritten obj)
		{
			//save pdf
			string path = await _mediaService.UploadImage(obj.file, Constants.Quiz);
			//then save quiz
			var quiz = new Quiz()
			{
				courseId = obj.CourseId,
				Description = obj.description,
				Name = obj.Name,
				FilePath = path
			};
			await _quizService.Add(quiz);
			return View(obj);
		}

		[HttpGet]
		public IActionResult GetAll(int id)//CourseId
		{
			string userId = GetUserId();
			var obj = new GetAllVM();
			var Qz = _quizService.GetAllByCourseId(id);
			var ListOfQuizes = new List<inhertQuiz>();
			//forloop in quizes to know if user take it or no and assign to VM
			foreach (var item in Qz)
			{
				var temp = new inhertQuiz()
				{
					courseId = item.courseId,
					Description = item.Description,
					FilePath = item.FilePath,
					Name = item.Name,
					StudentQuizzes = item.StudentQuizzes,
					Course = item.Course,
					Id = item.Id,
					Questions = item.Questions
				};
				temp.StudentTakedExam = _studentQuizService.StudentTakeExam(userId, item.Id);

				ListOfQuizes.Add(temp);
			}

			var students = _studentQuizService.GetStudents(id);
			obj.students = students;
			obj.quizzes = ListOfQuizes;
			return View(obj);
		}

		[HttpGet]//Quiz --
		public IActionResult Get(int id) //quiz id
		{
			DateTime startTime = DateTime.Now;
			HttpContext.Session.Set("StartTime", Encoding.UTF8.GetBytes(startTime.ToString()));

			// Calculate the end time of the exam (e.g., 1 hour time limit)
			DateTime endTime = startTime.AddSeconds(40);
			ViewBag.EndTime = endTime;

			var quiz = _quizService.Get(id);
			if (quiz.FilePath != string.Empty)
			{//pdf exam
			 //var pdfName = quiz.FileNameMaster;
			 //// string uploadedFolder = Path.Combine(hostingEnvironment.WebRootPath, "assets", "images", "Quiz");
			 //// string filePath = Path.Combine(uploadedFolder, pdfName);
			 //string pdfUrl = "/assets/images/Quiz/" + pdfName;

				//// Pass the pdfUrl to the view
				//ViewBag.PDF = pdfUrl;
				//ViewBag.Id = id;
			}
			return View(quiz);
		}


		[HttpPost]
		public async Task<IActionResult> Submit(int quizId, List<int> selectedAnswers)
		{
			int score = 0, maxScore = 0;
			//correcting exam
			string userId = GetUserId();
			var quiz = _quizService.Get(quizId);//including questions and options
			if (quiz.FilePath == string.Empty || quiz.FilePath == null)
			{
				score = _quizService.CalcMcq(quiz, userId, selectedAnswers);
				maxScore = quiz.Questions.Count;
			}
			//add in UserQuiz table
			var StudentQuiz = new StudentQuiz()
			{
				CourseId = quiz.courseId,
				ExamDegree = score,
				MaxDegree = maxScore,
				QuizId = quizId,
				StudentId = userId
			};
			await _studentQuizService.Add(StudentQuiz);

			return RedirectToAction("GetAll", quiz.courseId);
		}

		[HttpPost]
		public async Task<IActionResult> SubmitWritten(IFormFile File, int id)//QuizId (GetAll didn't get student when redirect)
		{//(GetAll didn't get student when redirect)
			string userId = GetUserId();
			var quiz = _quizService.Get(id);
			string path = await _mediaService.UploadImage(File, Constants.Quiz);//change to folder for students in quiz folder
			var StudentQuiz = new StudentQuiz()
			{
				CourseId = quiz.courseId,
				ExamDegree = 0,
				MaxDegree = 0,
				QuizId = quiz.Id,
				StudentId = userId,
				StudentAnswerPath = path
			};
			await _studentQuizService.Add(StudentQuiz);
			return RedirectToAction("GetAll", new { id = quiz.courseId });

		}

		[HttpGet]
		public async Task<IActionResult> CorrectWritten(int id)//CourseId
		{
			//StudentQuiz with Student
			var obj = _studentQuizService.GetAll(id);
			return View(obj);
		}
		//DisplayPdf
		[HttpGet]
		public IActionResult DisplayPdf(int id) //Student Quiz ID
		{
			var studentQuiz = _studentQuizService.GetById(id);
			return View(studentQuiz);
		}
		[HttpPost]
		public async Task<IActionResult> CorrectWritten(List<StudentQuiz> correctquiz)
		{
			//saving
			await _studentQuizService.CorrectingWritten(correctquiz);
			return View(correctquiz);
		}

		#endregion




		#region Private
		private string GetUserId()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var uId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (uId == null) return string.Empty;
			return uId.Value;
		}
		#endregion



	}
}

LMS/Controllers/UserController.cs
using LMS.Service.Abstract;
using LMS.ViewModels.User;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LMS.Controllers
{
    public class UserController : Controller
    {
        #region Fields
        private readonly IUserService _userService;

        #endregion

        #region Ctor
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        #endregion

        #region Actions


        [HttpGet]
        public async Task<IActionResult> EditProfile()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var id = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            var vm = await _userService.GetUserData(id);
            if (vm == null) return NotFound();
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> EditProfile(EditProfileVM editProfileVM)
        {
            if (ModelState.IsValid)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var id = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                editProfileVM.Id = id;
                await _userService.EditProfile(editProfileVM);
                //Success Message
            }

            return View(editProfileVM);
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordVM changePasswordVM)
        {
            if (ModelState.IsValid)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var id = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                changePasswordVM.Id = id;
                string response = await _userService.ChangePassword(changePasswordVM);
                if (response == "Success")
                {
                    //success message!
                    return RedirectToAction("EditProfile");
                }
                ModelState.AddModelError("", response);
            }
            return View(changePasswordVM);
        }


        #endregion


    }
}

LMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ar">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="~/css/edit.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
	<link rel="stylesheet" href="~/css/all.min.css">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@200;300;400;500;600&display=swap" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/bootstrap.min.css.map">
	<title>Master Academy</title>
</head>
<body>

	<!-- adminnnnn -->



	<div class="bg-body-tertiary show-animation">
		<div class="container animation">
			<nav class="navbar navbar-expand-lg bg-body-tertiary">

				<div class="container-fluid">
					@if (!User.Identity.IsAuthenticated)
					{
						<div class="ml-auto bttn login">
							<a asp-action="login" asp-controller="Account" class="btn my-2 my-sm-0 border-0 tr">تسجيل الدخول</a>
						</div>
					}
					else
					{
						<div class="ml-auto bttn login">
							<a  class="btn my-2 my-sm-0 border-0 tr">  @User.Identity.Name مرحبا</a>
						</div>
					}

					<button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse ml-auto justify-content-center link" id="navbarText">
						<ul class="navbar-nav ms-auto me-auto mb-2 mb-lg-0 align-items-lg-center">
							<li class="nav-item">

								<div class="dropdown">
									<a class="btn btn-light border mx-1 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="fa-solid fa-file-pdf "></i>
									</a>

									<ul class="dropdown-menu">
										<li><a class="dropdown-item" asp-action="index" asp-route-id="1" asp-controller="pdf">الصف الاول الثانوي</a></li>
										<li><a class="dropdown-item" asp-action="index" asp-route-id="2" asp-controller="pdf"> الصف الثاني الثانوي</a></li>
										<li><a class="dropdown-item" asp-action="index" asp-route-id="3" asp-controller="pdf"> الصف الثالث الثانوي </a></li>
									</ul>
								</div>

							</li>
							<li class="nav-item">
								<div class="dropdown">
									<a class="btn btn-light border mx-1  dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="fa-solid fa-book"></i>
									</a>

									<ul class="dropdown-menu">
										<li><a class="dropdown-item" asp-action="index" asp-route-id="1" asp-controller="Quiz">الصف الاول الثانوي</a></li>
										<li><a class="dropdown-item" asp-action="index" asp-route-id="2" asp-controller="Quiz"> الصف الثاني الثانوي</a></li>
										<li><a class="dropdown-item" asp-action="index" asp-route-id="3" asp-controller="Quiz"> الصف الثالث الثانوي </a></li>
									</ul>
								</div>
							</li>
							<li class="nav-item">
								<div class="dropdown">
									<a class="btn btn-light border mx-1 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="fa-solid fa-user-large"></i>
									</a>

									<ul class="dropdown-menu">
										<li><a class="dropdown-item" asp-action="EditProfile" asp-controller="User"> تعديل البروفايل </a></li>
										@if (User.Identity.IsAuthenticated)
										{
											<li><a class="dropdown-item" asp-action="LogOut" asp-controller="Account">   تسجيل الخروج</a></li>


										}

									</ul>
								</div>
							</li>


						</ul>

						<a class="navbar-brand d-none d-lg-block" asp-action="index" asp-controller="home">
							<img src="~/assets/images/Front/vector-background remove.png" alt="Logo" />
						</a>
					</div>
				</div>
			</nav>
		</div>

	</div>


	@RenderBody()










	<footer>
		<div>
			<div class="logo">
				<a href="https://www.facebook.com/wael.kabil.94">
					<i class="fa-brands fa-facebook"></i>
					<span class="name">facebook</span>
				</a>

				<a href="https://www.youtube.com/mrwaelkabeel4086">
					<i class="fa-brands fa-youtube"></i>
					<span class="name">youtube</span>
				</a>

				<a href="">
					<i class="fa-brands fa-whatsapp"></i>
					<span class="name">whatsapp</span>
				</a>
			</div>
			<h4> Developed By: Mohamed zidan, Ahmed samy </h4>
			<h4 class="last"> All Copy Rights Reserved  <span class="year"></span></h4>
		</div>
	</footer>




	<!-- <script src="js/all.min.js"></script> -->
</body>

<script src="~/js/code.js"></script>
<script src="~/js/pdf.js"></script>
<script src="~/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>



@await RenderSectionAsync("Scripts", required: false)
</html>