LMS/Models/Entities/Course.cs
namespace LMS.Models.Entities
{
    public class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? ImgPath { get; set; }
        public int Price { get; set; }

        public string? Description { get; set; }

        public bool free { get; set; }

        public ICollection<CourseStudent> CourseStudents { get; set; } = new List<CourseStudent>();
        public ICollection<CourseRequest> CourseRequests { get; set; } = new List<CourseRequest>();
        public ICollection<StudentQuiz> StudentQuizzes { get; set; } = new List<StudentQuiz>();
        public ICollection<Material> Materials { get; set; } = new List<Material>(); // Add missing relationship
        public ICollection<Video> Videos { get; set; } = new List<Video>(); // Add missing relationship
    }
}

LMS/ViewModels/Course/AddCourseVM.cs
namespace LMS.ViewModels.Course
{
    public class AddCourseVM
    {
        public string Name { get; set; }

        public int Price { get; set; }
        public string? Description { get; set; }

        public IFormFile file { get; set; }
    }
}

LMS/ViewModels/Course/GetAllCoursesForAdminVM.cs
namespace LMS.ViewModels.Course
{
    public class GetAllCoursesForAdminVM
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Price { get; set; }

        public int studentsIn { get; set; }
        public string imgPath { get; set; }
    }
}

LMS/ViewModels/Course/GetCourseVM.cs
namespace LMS.ViewModels.Course
{
    public class GetCourseVM
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Price { get; set; }

        public string? Description { get; set; }

        public bool CanEnroll { get; set; }
        public string imgPath { get; set; }
    }
}

LMS/Controllers/CourseController.cs
using LMS.Service.Abstract;
using LMS.ViewModels.Course;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LMS.Controllers
{
    public class CourseController : Controller
    {
        #region Fields
        private readonly ICourseService _courseService;
        private readonly ICourseStudentService _courseStudentService;
        private readonly IVideoService _videoService;
        #endregion

        #region Ctor
        public CourseController(ICourseService courseService, ICourseStudentService courseStudentService, IVideoService videoService)
        {
            _courseService = courseService;
            _courseStudentService = courseStudentService;
            _videoService = videoService;
        }
        #endregion

        #region Actions
        [HttpGet]
        public IActionResult Index(int id)//page that contain videos
        {
            var videos = _videoService.getCourseVideos(id);
            ViewBag.CourseId = id;
            return View(videos);
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var x = _courseService.GetAll();
            var res = new List<GetAllCoursesForAdminVM>();
            foreach (var item in x)
            {
                int number = _courseStudentService.GetStudentsCountInCourseById(item.Id);
                var temp = new GetAllCoursesForAdminVM()
                {
                    Id = item.Id,
                    imgPath = item.imgPath,
                    Name = item.Name,
                    Price = item.Price,
                    studentsIn = number
                };
                res.Add(temp);
            }
            return View(res);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddCourseVM courseVM)
        {
            await _courseService.AddCourse(courseVM);
            //tempData To save successfully
            return View();
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            var course = _courseService.GetById(id);
            string userId = GetUserId();
            if (userId != string.Empty)
            {
                course.CanEnroll = _courseStudentService.StudentInCourse(id, GetUserId());
            }
            else
            {
                course.CanEnroll = true;
            }

            if (course == null)
            {
                return RedirectToAction("index", "Home");
            }
            return View(course);
        }

        [HttpPost]
        public IActionResult Accept(int id)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _courseService.Delete(id);
            return RedirectToAction("GetAll");
        }

        #endregion

        #region Private
        private string GetUserId()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var uId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (uId == null) return string.Empty;
            return uId.Value;
        }
        #endregion
    }
}

LMS/Controllers/CourseRequestController.cs
using LMS.Service.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LMS.Controllers
{
    public class CourseRequestController : Controller
    {
        #region Fields
        private readonly ICourseRequestService _courseRequestService;

        #endregion

        #region Ctor
        public CourseRequestController(ICourseRequestService courseRequestService)
        {
            _courseRequestService = courseRequestService;
        }
        #endregion

        #region Actions
        //  [HttpPost]
        public async Task<IActionResult> Enroll(int id)//course id
        {
            var userId = GetUserId();
            if (userId == string.Empty)
            {
                return RedirectToAction("Login", "Account");
            }
            //service to check if in Course request => nothing , Add to table--- Free Course=> Assign
            string response = await _courseRequestService.Add(id, userId);

            return RedirectToAction("index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var CR = await _courseRequestService.GetAll();
            return View(CR);
        }
        public async Task<IActionResult> Delete(int id)
        {
            string res = await _courseRequestService.Delete(id);
            //check res
            return RedirectToAction("GetAll");
        }
        public async Task<IActionResult> Accept(int id)
        {
            string res = await _courseRequestService.Accept(id);
            //check res
            return RedirectToAction("GetAll");
        }




        #endregion



        #region Private
        private string GetUserId()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var uId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (uId == null) return string.Empty;
            return uId.Value;
        }
        #endregion
    }
}

LMS/Controllers/QuizController.cs
using LMS.Helper;
using LMS.Models.Entities;
using LMS.Service.Abstract;
using LMS.ViewModels.QuizVM;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;

namespace LMS.Controllers
{
	public class QuizController : Controller
	{
		#region Fields
		private readonly IQuizService _quizService;
		private readonly IStudentQuizService _studentQuizService;
		private readonly IMediaService _mediaService;

		#endregion

		#region Ctor
		public QuizController(IQuizService quizService, IStudentQuizService studentQuizService, IMediaService mediaService)
		{
			_quizService = quizService;
			_studentQuizService = studentQuizService;
			_mediaService = mediaService;
		}
		#endregion

		#region Actions



		[HttpGet]
		public IActionResult Add(int id)
		{
			ViewBag.id = id;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Add(Quiz quiz)//make id = 0 
		{
			quiz.Id = 0;
			await _quizService.Add(quiz);
			return View();
		}
		[HttpGet]
		public IActionResult AddWritten(int id)
		{
			var obj = new AddWritten()
			{
				CourseId = id
			};
			return View(obj);
		}
		[HttpPost]
		public async Task<IActionResult> AddWritten(AddWritten obj)
		{
			//save pdf
			string path = await _mediaService.UploadImage(obj.file, Constants.Quiz);
			//then save quiz
			var quiz = new Quiz()
			{
				courseId = obj.CourseId,
				Description = obj.description,
				Name = obj.Name,
				FilePath = path
			};
			await _quizService.Add(quiz);
			return View(obj);
		}

		[HttpGet]
		public IActionResult GetAll(int id)//CourseId
		{
			string userId = GetUserId();
			var obj = new GetAllVM();
			var Qz = _quizService.GetAllByCourseId(id);
			var ListOfQuizes = new List<inhertQuiz>();
			//forloop in quizes to know if user take it or no and assign to VM
			foreach (var item in Qz)
			{
				var temp = new inhertQuiz()
				{
					courseId = item.courseId,
					Description = item.Description,
					FilePath = item.FilePath,
					Name = item.Name,
					StudentQuizzes = item.StudentQuizzes,
					Course = item.Course,
					Id = item.Id,
					Questions = item.Questions
				};
				temp.StudentTakedExam = _studentQuizService.StudentTakeExam(userId, item.Id);

				ListOfQuizes.Add(temp);
			}

			var students = _studentQuizService.GetStudents(id);
			obj.students = students;
			obj.quizzes = ListOfQuizes;
			return View(obj);
		}

		[HttpGet]//Quiz --
		public IActionResult Get(int id) //quiz id
		{
			DateTime startTime = DateTime.Now;
			HttpContext.Session.Set("StartTime", Encoding.UTF8.GetBytes(startTime.ToString()));

			// Calculate the end time of the exam (e.g., 1 hour time limit)
			DateTime endTime = startTime.AddSeconds(40);
			ViewBag.EndTime = endTime;

			var quiz = _quizService.Get(id);
			if (quiz.FilePath != string.Empty)
			{//pdf exam
			 //var pdfName = quiz.FileNameMaster;
			 //// string uploadedFolder = Path.Combine(hostingEnvironment.WebRootPath, "assets", "images", "Quiz");
			 //// string filePath = Path.Combine(uploadedFolder, pdfName);
			 //string pdfUrl = "/assets/images/Quiz/" + pdfName;

				//// Pass the pdfUrl to the view
				//ViewBag.PDF = pdfUrl;
				//ViewBag.Id = id;
			}
			return View(quiz);
		}


		[HttpPost]
		public async Task<IActionResult> Submit(int quizId, List<int> selectedAnswers)
		{
			int score = 0, maxScore = 0;
			//correcting exam
			string userId = GetUserId();
			var quiz = _quizService.Get(quizId);//including questions and options
			if (quiz.FilePath == string.Empty || quiz.FilePath == null)
			{
				score = _quizService.CalcMcq(quiz, userId, selectedAnswers);
				maxScore = quiz.Questions.Count;
			}
			//add in UserQuiz table
			var StudentQuiz = new StudentQuiz()
			{
				CourseId = quiz.courseId,
				ExamDegree = score,
				MaxDegree = maxScore,
				QuizId = quizId,
				StudentId = userId
			};
			await _studentQuizService.Add(StudentQuiz);

			return RedirectToAction("GetAll", quiz.courseId);
		}

		[HttpPost]
		public async Task<IActionResult> SubmitWritten(IFormFile File, int id)//QuizId (GetAll didn't get student when redirect)
		{//(GetAll didn't get student when redirect)
			string userId = GetUserId();
			var quiz = _quizService.Get(id);
			string path = await _mediaService.UploadImage(File, Constants.Quiz);//change to folder for students in quiz folder
			var StudentQuiz = new StudentQuiz()
			{
				CourseId = quiz.courseId,
				ExamDegree = 0,
				MaxDegree = 0,
				QuizId = quiz.Id,
				StudentId = userId,
				StudentAnswerPath = path
			};
			await _studentQuizService.Add(StudentQuiz);
			return RedirectToAction("GetAll", new { id = quiz.courseId });

		}

		[HttpGet]
		public async Task<IActionResult> CorrectWritten(int id)//CourseId
		{
			//StudentQuiz with Student
			var obj = _studentQuizService.GetAll(id);
			return View(obj);
		}
		//DisplayPdf
		[HttpGet]
		public IActionResult DisplayPdf(int id) //Student Quiz ID
		{
			var studentQuiz = _studentQuizService.GetById(id);
			return View(studentQuiz);
		}
		[HttpPost]
		public async Task<IActionResult> CorrectWritten(List<StudentQuiz> correctquiz)
		{
			//saving
			await _studentQuizService.CorrectingWritten(correctquiz);
			return View(correctquiz);
		}

		#endregion




		#region Private
		private string GetUserId()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var uId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (uId == null) return string.Empty;
			return uId.Value;
		}
		#endregion



	}
}

LMS/Controllers/VideoController.cs
using LMS.Models.Entities;
using LMS.Service.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace LMS.Controllers
{
    public class VideoController : Controller
    {
        #region Fields
        private readonly IVideoService _videoService;
        #endregion

        #region Ctor
        public VideoController(IVideoService videoService)
        {
            _videoService = videoService;
        }
        #endregion

        #region Actions
        [HttpPost]
        public async Task<IActionResult> Add([Bind("Name,VideoPath,CourseId")] Video video)
        {
            await _videoService.Add(video);
            return RedirectToAction("Index", "Course", new { id = video.CourseId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _videoService.Delete(id);
            return RedirectToAction("Index", "Course", new { id = id });
        }

        #endregion

    }
}

LMS/Views/Course/Add.cshtml
@model LMS.ViewModels.Course.AddCourseVM;
@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<div class="container">

    <form method="post" enctype="multipart/form-data">

        <input type="file" asp-for="@Model.file" name="file" class="form-control rounded-4 fileInput" placeholder="ve" required>

        <div class="input-box">
            <input type="text" asp-for="@Model.Name" name="Name" class="title " placeholder="Course Name" required>


        </div>
        <div class="input-box">
            <textarea type="text" asp-for="@Model.Description" name="Description" class="title " placeholder="Course Name" required></textarea>


        </div>
        <br />
        <div class="input-box">
            <input type="text" class="price" asp-for="@Model.Price" name="Price" placeholder="Price" required>

        </div>
        <button type="submit" class="btn"> Add </button>
    </form>
</div>

LMS/Views/Course/Detail.cshtml
@model LMS.ViewModels.Course.GetCourseVM
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<form>
    <div class="input-box">
        <h2>@Model.Name</h2>
        <p>@Model.Description</p>
        @if (Model.Price != 0)
        {
            <p>
                Model.Price
            </p>
        }
        else
        {
            <p>Free</p>
        }
        <img src="~/@Model.imgPath" width="200" height="200" />
        @if (Model.CanEnroll)
        {
            <a asp-action="index" asp-controller="Course" asp-route-id="@Model.Id" class="btn btn-primary">Go To Course</a>

        }
        else
        {
            <a asp-action="Enroll" asp-controller="CourseRequest" asp-route-id="@Model.Id" class="btn btn-primary">Enroll</a>
        }

    </div>
</form>

LMS/Views/Course/GetAll.cshtml
@model IEnumerable<LMS.ViewModels.Course.GetAllCoursesForAdminVM>

@{
    ViewData["Title"] = "MyStudents";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">



<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    input[type=text] {
        width: 150px;
        padding: 5px;
    }

    select {
        padding: 5px;
    }

    input[type=submit] {
        padding: 5px 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        cursor: pointer;
    }
</style>

<body>

    <form id="searchForm">
        <label for="name">Search by Name:</label>
        <input type="text" id="name" name="name" placeholder="Enter name...">
        <input type="submit" value="Search">
    </form>

    <table id="studentTable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>pic</th>
                <th>students</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <form method="post">

                @foreach (var item in Model)
                {

                <tr>
                    <td hidden>
                            @item.Id
                    </td>
                    <td>
                            @item.Name
                    </td>
                    <td>
                            @item.Price
                    </td>
                    <td>
                        <img src="~/@item.imgPath" height="100" width="100" />
                    </td>
                    <td>
                            @item.studentsIn
                    </td>
                    <td>
                        <button type="submit" asp-action="Delete" asp-controller="Course" asp-route-id="@item.Id" class="btn btn-danger">Delete</button>

                    </td>
                </tr>
                }
            </form>

        </tbody>
    </table>

    <script>
        const form = document.getElementById('searchForm');
        const table = document.getElementById('studentTable');

        form.addEventListener('input', function (e) {
            const nameInput = document.getElementById('name');
            const degreeInput = document.getElementById('degree');

            const nameFilter = nameInput.value.toLowerCase();
            const degreeFilter = degreeInput.value.toLowerCase();

            const rows = table.getElementsByTagName('tr');

            for (let i = 1; i < rows.length; i++) {
                const name = rows[i].getElementsByTagName('td')[0].innerText.toLowerCase();
                const degree = rows[i].getElementsByTagName('td')[1].innerText.toLowerCase();

                if ((nameFilter === '' || name.includes(nameFilter)) &&
                    (degreeFilter === '' || degree === degreeFilter)) {
                    rows[i].style.display = '';
                } else {
                    rows[i].style.display = 'none';
                }
            }
        });
    </script>



</body>

LMS/Views/Course/Index.cshtml
@model IEnumerable<LMS.Models.Entities.Video>


@{
    ViewData["Title"] = "CoursePage";
}



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/edit.css">
    <link rel="stylesheet" href="~/css/frist.css">
    <link rel="stylesheet" href="~/css/exam.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@200;300;400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/all.min.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <title>فيدوهات</title>
</head>
<body>

    @* البتاعه المدوره *@
    <nav class="menu">
        <input type="checkbox" href="#" class="menu-open" name="menu-open" id="menu-open" placeholder="..">
        <label class="menu-open-button" for="menu-open">
            <span class="lines line-1"></span>
            <span class="lines line-2"></span>
            <span class="lines line-3"></span>
        </label>
        <a asp-action="GetAll" asp-controller="material" asp-route-id="@ViewBag.CourseId"  class="menu-item gray"> <i class="fa-regular fa-file-pdf"></i> </a>
        <a asp-action="Add" asp-controller="Quiz" asp-route-id="@ViewBag.CourseId" class="menu-item gray"> <i class="fa-solid fa-pen"></i> </a>
       
        <a asp-action="index" asp-controller="material"  asp-route-id="@ViewBag.CourseId"  class="menu-item gray"> <i class="fa-solid fa-person-circle-question"></i></a>
        <a asp-action="GetAll" asp-controller="Quiz" asp-route-id="@ViewBag.CourseId" class="menu-item gray"><i class="fa-solid fa-file-lines"></i></a>
    </nav>

    <partial name="partial/_AddVideo" />



    @if (Model.Count() > 0)
    {
        <form method="post" asp-controller="video" asp-action="Delete">

            <div id="videoContainer">

                @foreach (var vid in Model)
                {
                    <div class="links">
                        <h1>@vid.Name</h1>

                        <button onclick="openVideo('@vid.VideoPath')">Open Video</button>
                        @*Hidden just for admin*@
                        <button type="submit" asp-action="Delete" asp-controller="Video" asp-route-id="@vid.Id" class="btn btn-danger">Delete</button>
                    </div>
                }
            </div>
        </form>
    }


    <script>
        let menu = document.querySelector(".menu-open-button");
        menu.addEventListener("click", function () {
            let x = document.querySelector(".menu")
            x.classList.toggle("toggle");

        })


    </script>



    <script src="~/js/coll-vedio.js"></script>
</body>